language: node_js
node_js:
  - "6"
  - "4.4.5"
services:
  - postgresql
before_script:
  - createuser gamifyeducation -s -r -d -w
  - psql -c 'create database gamifyeducation;' -U postgres
  - psql -c "alter user \"gamifyeducation\" with password 'gamifyeducation';" -U postgres
  - psql -c "alter database \"gamifyeducation\" owner to \"gamifyeducation\";" -U postgres
