import React, { Component } from 'react';


const states = ([
    <option value="AL"  key="AL">Alabama</option>,
    <option value="AK"  key="AK">Alaska</option>,
    <option value="AZ"  key="AZ">Arizona</option>,
    <option value="AR"  key="AR">Arkansas</option>,
    <option value="CA"  key="CA">California</option>,
    <option value="CO"  key="CO">Colorado</option>,
    <option value="CT"  key="CT">Connecticut</option>,
    <option value="DE"  key="DE">Delaware</option>,
    <option value="DC"  key="DC">District Of Columbia</option>,
    <option value="FL"  key="FL">Florida</option>,
    <option value="GA"  key="GA">Georgia</option>,
    <option value="HI"  key="HI">Hawaii</option>,
    <option value="ID"  key="ID">Idaho</option>,
    <option value="IL"  key="IL">Illinois</option>,
    <option value="IN"  key="IN">Indiana</option>,
    <option value="IA"  key="IA">Iowa</option>,
    <option value="KS"  key="KS">Kansas</option>,
    <option value="KY"  key="KY">Kentucky</option>,
    <option value="LA"  key="LA">Louisiana</option>,
    <option value="ME"  key="ME">Maine</option>,
    <option value="MD"  key="MD">Maryland</option>,
    <option value="MA"  key="MA">Massachusetts</option>,
    <option value="MI"  key="MI">Michigan</option>,
    <option value="MN"  key="MN">Minnesota</option>,
    <option value="MS"  key="MS">Mississippi</option>,
    <option value="MO"  key="MO">Missouri</option>,
    <option value="MT"  key="MT">Montana</option>,
    <option value="NE"  key="NE">Nebraska</option>,
    <option value="NV"  key="NV">Nevada</option>,
    <option value="NH"  key="NH">New Hampshire</option>,
    <option value="NJ"  key="NJ">New Jersey</option>,
    <option value="NM"  key="NM">New Mexico</option>,
    <option value="NY"  key="NY">New York</option>,
    <option value="NC"  key="NC">North Carolina</option>,
    <option value="ND"  key="ND">North Dakota</option>,
    <option value="OH"  key="OH">Ohio</option>,
    <option value="OK"  key="OK">Oklahoma</option>,
    <option value="OR"  key="OR">Oregon</option>,
    <option value="PA"  key="PA">Pennsylvania</option>,
    <option value="RI"  key="RI">Rhode Island</option>,
    <option value="SC"  key="SC">South Carolina</option>,
    <option value="SD"  key="SD">South Dakota</option>,
    <option value="TN"  key="TN">Tennessee</option>,
    <option value="TX"  key="TX">Texas</option>,
    <option value="UT"  key="UT">Utah</option>,
    <option value="VT"  key="VT">Vermont</option>,
    <option value="VA"  key="VA">Virginia</option>,
    <option value="WA"  key="WA">Washington</option>,
    <option value="WV"  key="WV">West Virginia</option>,
    <option value="WI"  key="WI">Wisconsin</option>,
    <option value="WY"  key="WY">Wyoming</option>,
  ]
);

export default states;
