import React,
 {Component} from 'react';

import * as _ from 'lodash';

const htmlStreetTypes = ([
  <option value='ALY' key='ALY'>ALY </option>,
  <option value='ANX' key='ANX'>ANX </option>,
  <option value='ARC' key='ARC'>ARC </option>,
  <option value='AVE' key='AVE'>AVE </option>,
  <option value='BYU' key='BYU'>BYU </option>,
  <option value='BCH' key='BCH'>BCH </option>,
  <option value='BND' key='BND'>BND </option>,
  <option value='BLF' key='BLF'>BLF </option>,
  <option value='BLFS' key='BLFS'>BLFS </option>,
  <option value='BTM' key='BTM'>BTM </option>,
  <option value='BLVD' key='BLVD'>BLVD </option>,
  <option value='BR' key='BR'>BR </option>,
  <option value='BRG' key='BRG'>BRG </option>,
  <option value='BRK' key='BRK'>BRK </option>,
  <option value='BRKS' key='BRKS'>BRKS </option>,
  <option value='BG' key='BG'>BG </option>,
  <option value='BGS' key='BGS'>BGS </option>,
  <option value='BYP' key='BYP'>BYP </option>,
  <option value='CP' key='CP'>CP </option>,
  <option value='CYN' key='CYN'>CYN </option>,
  <option value='CPE' key='CPE'>CPE </option>,
  <option value='CSWY' key='CSWY'>CSWY </option>,
  <option value='CTR' key='CTR'>CTR </option>,
  <option value='CTRS' key='CTRS'>CTRS </option>,
  <option value='CIR' key='CIR'>CIR </option>,
  <option value='CIRS' key='CIRS'>CIRS </option>,
  <option value='CLF' key='CLF'>CLF </option>,
  <option value='CLFS' key='CLFS'>CLFS </option>,
  <option value='CLB' key='CLB'>CLB </option>,
  <option value='CMN' key='CMN'>CMN </option>,
  <option value='CMNS' key='CMNS'>CMNS </option>,
  <option value='COR' key='COR'>COR </option>,
  <option value='CORS' key='CORS'>CORS </option>,
  <option value='CRSE' key='CRSE'>CRSE </option>,
  <option value='CT' key='CT'>CT </option>,
  <option value='CTS' key='CTS'>CTS </option>,
  <option value='CV' key='CV'>CV </option>,
  <option value='CVS' key='CVS'>CVS </option>,
  <option value='CRK' key='CRK'>CRK </option>,
  <option value='CRES' key='CRES'>CRES </option>,
  <option value='CRST' key='CRST'>CRST </option>,
  <option value='XING' key='XING'>XING </option>,
  <option value='XRD' key='XRD'>XRD </option>,
  <option value='XRDS' key='XRDS'>XRDS </option>,
  <option value='CURV' key='CURV'>CURV </option>,
  <option value='DL' key='DL'>DL </option>,
  <option value='DM' key='DM'>DM </option>,
  <option value='DV' key='DV'>DV </option>,
  <option value='DR' key='DR'>DR </option>,
  <option value='DRS' key='DRS'>DRS </option>,
  <option value='EST' key='EST'>EST </option>,
  <option value='ESTS' key='ESTS'>ESTS </option>,
  <option value='EXPY' key='EXPY'>EXPY </option>,
  <option value='EXT' key='EXT'>EXT </option>,
  <option value='EXTS' key='EXTS'>EXTS </option>,
  <option value='FALL' key='FALL'>FALL </option>,
  <option value='FLS' key='FLS'>FLS </option>,
  <option value='FRY' key='FRY'>FRY </option>,
  <option value='FLD' key='FLD'>FLD </option>,
  <option value='FLDS' key='FLDS'>FLDS </option>,
  <option value='FLT' key='FLT'>FLT </option>,
  <option value='FLTS' key='FLTS'>FLTS </option>,
  <option value='FRD' key='FRD'>FRD </option>,
  <option value='FRDS' key='FRDS'>FRDS </option>,
  <option value='FRST' key='FRST'>FRST </option>,
  <option value='FRG' key='FRG'>FRG </option>,
  <option value='FRGS' key='FRGS'>FRGS </option>,
  <option value='FRK' key='FRK'>FRK </option>,
  <option value='FRKS' key='FRKS'>FRKS </option>,
  <option value='FT' key='FT'>FT </option>,
  <option value='FWY' key='FWY'>FWY </option>,
  <option value='GDN' key='GDN'>GDN </option>,
  <option value='GDNS' key='GDNS'>GDNS </option>,
  <option value='GTWY' key='GTWY'>GTWY </option>,
  <option value='GLN' key='GLN'>GLN </option>,
  <option value='GLNS' key='GLNS'>GLNS </option>,
  <option value='GRN' key='GRN'>GRN </option>,
  <option value='GRNS' key='GRNS'>GRNS </option>,
  <option value='GRV' key='GRV'>GRV </option>,
  <option value='GRVS' key='GRVS'>GRVS </option>,
  <option value='HBR' key='HBR'>HBR </option>,
  <option value='HBRS' key='HBRS'>HBRS </option>,
  <option value='HVN' key='HVN'>HVN </option>,
  <option value='HTS' key='HTS'>HTS </option>,
  <option value='HWY' key='HWY'>HWY </option>,
  <option value='HL' key='HL'>HL </option>,
  <option value='HLS' key='HLS'>HLS </option>,
  <option value='HOLW' key='HOLW'>HOLW </option>,
  <option value='INLT' key='INLT'>INLT </option>,
  <option value='IS' key='IS'>IS </option>,
  <option value='ISS' key='ISS'>ISS </option>,
  <option value='ISLE' key='ISLE'>ISLE </option>,
  <option value='JCT' key='JCT'>JCT </option>,
  <option value='JCTS' key='JCTS'>JCTS </option>,
  <option value='KY' key='KY'>KY </option>,
  <option value='KYS' key='KYS'>KYS </option>,
  <option value='KNL ' key='KNL '>KNL  </option>,
  <option value='KNLS' key='KNLS'>KNLS </option>,
  <option value='LK' key='LK'>LK </option>,
  <option value='LKS' key='LKS'>LKS </option>,
  <option value='LAND' key='LAND'>LAND </option>,
  <option value='LNDG' key='LNDG'>LNDG </option>,
  <option value='LN' key='LN'>LN </option>,
  <option value='LGT' key='LGT'>LGT </option>,
  <option value='LGTS' key='LGTS'>LGTS </option>,
  <option value='LF' key='LF'>LF </option>,
  <option value='LCK' key='LCK'>LCK </option>,
  <option value='LCKS' key='LCKS'>LCKS </option>,
  <option value='LDG' key='LDG'>LDG </option>,
  <option value='LOOP' key='LOOP'>LOOP </option>,
  <option value='MALL' key='MALL'>MALL </option>,
  <option value='MNR' key='MNR'>MNR </option>,
  <option value='MNRS' key='MNRS'>MNRS </option>,
  <option value='MDW' key='MDW'>MDW </option>,
  <option value='MDWS' key='MDWS'>MDWS </option>,
  <option value='MEWS' key='MEWS'>MEWS </option>,
  <option value='ML' key='ML'>ML </option>,
  <option value='MLS' key='MLS'>MLS </option>,
  <option value='MSN' key='MSN'>MSN </option>,
  <option value='MTWY' key='MTWY'>MTWY </option>,
  <option value='MT' key='MT'>MT </option>,
  <option value='MTN' key='MTN'>MTN </option>,
  <option value='MTNS' key='MTNS'>MTNS </option>,
  <option value='NCK' key='NCK'>NCK </option>,
  <option value='ORCH' key='ORCH'>ORCH </option>,
  <option value='OVAL' key='OVAL'>OVAL </option>,
  <option value='OPAS' key='OPAS'>OPAS </option>,
  <option value='PARK' key='PARK'>PARK </option>,
  <option value='PKWY' key='PKWY'>PKWY </option>,
  <option value='PASS' key='PASS'>PASS </option>,
  <option value='PSGE' key='PSGE'>PSGE </option>,
  <option value='PATH' key='PATH'>PATH </option>,
  <option value='PIKE' key='PIKE'>PIKE </option>,
  <option value='PNE ' key='PNE '>PNE  </option>,
  <option value='PNES' key='PNES'>PNES </option>,
  <option value='PL' key='PL'>PL </option>,
  <option value='PLN' key='PLN'>PLN </option>,
  <option value='PLNS' key='PLNS'>PLNS </option>,
  <option value='PLZ' key='PLZ'>PLZ </option>,
  <option value='PT' key='PT'>PT </option>,
  <option value='PTS' key='PTS'>PTS </option>,
  <option value='PRT' key='PRT'>PRT </option>,
  <option value='PRTS' key='PRTS'>PRTS </option>,
  <option value='PR' key='PR'>PR </option>,
  <option value='RADL' key='RADL'>RADL </option>,
  <option value='RAMP' key='RAMP'>RAMP </option>,
  <option value='RNCH' key='RNCH'>RNCH </option>,
  <option value='RPD' key='RPD'>RPD </option>,
  <option value='RPDS' key='RPDS'>RPDS </option>,
  <option value='RST' key='RST'>RST </option>,
  <option value='RDG' key='RDG'>RDG </option>,
  <option value='RDGS' key='RDGS'>RDGS </option>,
  <option value='RIV' key='RIV'>RIV </option>,
  <option value='RD' key='RD'>RD </option>,
  <option value='RDS' key='RDS'>RDS </option>,
  <option value='RTE' key='RTE'>RTE </option>,
  <option value='ROW' key='ROW'>ROW </option>,
  <option value='RUE' key='RUE'>RUE </option>,
  <option value='RUN' key='RUN'>RUN </option>,
  <option value='SHL' key='SHL'>SHL </option>,
  <option value='SHLS' key='SHLS'>SHLS </option>,
  <option value='SHR' key='SHR'>SHR </option>,
  <option value='SHRS' key='SHRS'>SHRS </option>,
  <option value='SKWY' key='SKWY'>SKWY </option>,
  <option value='SPG' key='SPG'>SPG </option>,
  <option value='SPGS' key='SPGS'>SPGS </option>,
  <option value='SPUR' key='SPUR'>SPUR </option>,
  <option value='SQ' key='SQ'>SQ </option>,
  <option value='SQS' key='SQS'>SQS </option>,
  <option value='STA' key='STA'>STA </option>,
  <option value='STRA' key='STRA'>STRA </option>,
  <option value='STRM' key='STRM'>STRM </option>,
  <option value='ST' key='ST'>ST </option>,
  <option value='STS' key='STS'>STS </option>,
  <option value='SMT' key='SMT'>SMT </option>,
  <option value='TER' key='TER'>TER </option>,
  <option value='TRWY' key='TRWY'>TRWY </option>,
  <option value='TRCE' key='TRCE'>TRCE </option>,
  <option value='TRAK' key='TRAK'>TRAK </option>,
  <option value='TRFY' key='TRFY'>TRFY </option>,
  <option value='TRL' key='TRL'>TRL </option>,
  <option value='TRLR' key='TRLR'>TRLR </option>,
  <option value='TUNL' key='TUNL'>TUNL </option>,
  <option value='TPKE' key='TPKE'>TPKE </option>,
  <option value='UPAS' key='UPAS'>UPAS </option>,
  <option value='UN' key='UN'>UN </option>,
  <option value='UNS' key='UNS'>UNS </option>,
  <option value='VLY' key='VLY'>VLY </option>,
  <option value='VLYS' key='VLYS'>VLYS </option>,
  <option value='VIA' key='VIA'>VIA </option>,
  <option value='VW' key='VW'>VW </option>,
  <option value='VWS' key='VWS'>VWS </option>,
  <option value='VLG' key='VLG'>VLG </option>,
  <option value='VLGS' key='VLGS'>VLGS </option>,
  <option value='VL' key='VL'>VL </option>,
  <option value='VIS' key='VIS'>VIS </option>,
  <option value='WALK' key='WALK'>WALK </option>,
  <option value='WALL' key='WALL'>WALL </option>,
  <option value='WAY' key='WAY'>WAY </option>,
  <option value='WAYS' key='WAYS'>WAYS </option>,
  <option value='WL ' key='WL '>WL  </option>,
  <option value='WLS' key='WLS'>WLS </option>
]);

const streetTypes = [
  'ALY',
  'ANX',
  'ARC',
  'AVE',
  'BYU',
  'BCH',
  'BND',
  'BLF',
  'BLFS',
  'BTM',
  'BLVD',
  'BR',
  'BRG',
  'BRK',
  'BRKS',
  'BG',
  'BGS',
  'BYP',
  'CP',
  'CYN',
  'CPE',
  'CSWY',
  'CTR',
  'CTRS',
  'CIR',
  'CIRS',
  'CLF',
  'CLFS',
  'CLB',
  'CMN',
  'CMNS',
  'COR',
  'CORS',
  'CRSE',
  'CT',
  'CTS',
  'CV',
  'CVS',
  'CRK',
  'CRES',
  'CRST',
  'XING',
  'XRD',
  'XRDS',
  'CURV',
  'DL',
  'DM',
  'DV',
  'DR',
  'DRS',
  'EST',
  'ESTS',
  'EXPY',
  'EXT',
  'EXTS',
  'FALL',
  'FLS',
  'FRY',
  'FLD',
  'FLDS',
  'FLT',
  'FLTS',
  'FRD',
  'FRDS',
  'FRST',
  'FRG',
  'FRGS',
  'FRK',
  'FRKS',
  'FT',
  'FWY',
  'GDN',
  'GDNS',
  'GTWY',
  'GLN',
  'GLNS',
  'GRN',
  'GRNS',
  'GRV',
  'GRVS',
  'HBR',
  'HBRS',
  'HVN',
  'HTS',
  'HWY',
  'HL',
  'HLS',
  'HOLW',
  'INLT',
  'IS',
  'ISS',
  'ISLE',
  'JCT',
  'JCTS',
  'KY',
  'KYS',
  'KNL' ,
  'KNLS',
  'LK',
  'LKS',
  'LAND',
  'LNDG',
  'LN',
  'LGT',
  'LGTS',
  'LF',
  'LCK',
  'LCKS',
  'LDG',
  'LOOP',
  'MALL',
  'MNR',
  'MNRS',
  'MDW',
  'MDWS',
  'MEWS',
  'ML',
  'MLS',
  'MSN',
  'MTWY',
  'MT',
  'MTN',
  'MTNS',
  'NCK',
  'ORCH',
  'OVAL',
  'OPAS',
  'PARK',
  'PKWY',
  'PASS',
  'PSGE',
  'PATH',
  'PIKE',
  'PNE' ,
  'PNES',
  'PL',
  'PLN',
  'PLNS',
  'PLZ',
  'PT',
  'PTS',
  'PRT',
  'PRTS',
  'PR',
  'RADL',
  'RAMP',
  'RNCH',
  'RPD',
  'RPDS',
  'RST',
  'RDG',
  'RDGS',
  'RIV',
  'RD',
  'RDS',
  'RTE',
  'ROW',
  'RUE',
  'RUN',
  'SHL',
  'SHLS',
  'SHR',
  'SHRS',
  'SKWY',
  'SPG',
  'SPGS',
  'SPUR',
  'SQ',
  'SQS',
  'STA',
  'STRA',
  'STRM',
  'ST',
  'STS',
  'SMT',
  'TER',
  'TRWY',
  'TRCE',
  'TRAK',
  'TRFY',
  'TRL',
  'TRLR',
  'TUNL',
  'TPKE',
  'UPAS',
  'UN',
  'UNS',
  'VLY',
  'VLYS',
  'VIA',
  'VW',
  'VWS',
  'VLG',
  'VLGS',
  'VL',
  'VIS',
  'WALK',
  'WALL',
  'WAY',
  'WAYS',
  'WL' ,
  'WLS',
]

const fullStreetTypeName = [
  "ALLEY ",
  "ANEX ",
  "ARCADE ",
  "AVENUE ",
  "BAYOU ",
  "BEACH ",
  "BEND ",
  "BLUFF ",
  "BLUFFS ",
  "BOTTOM   ",
  "BOULEVARD ",
  "BRANCH ",
  "BRIDGE ",
  "BROOK ",
  "BROOKS ",
  "BURG ",
  "BURGS ",
  "BYPASS ",
  "CAMP ",
  "CANYON   ",
  "CAPE   ",
  "CAUSEWAY   ",
  "CENTER ",
  "CENTERS ",
  "CIRCLE ",
  "CIRCLES ",
  "CLIFF ",
  "CLIFFS ",
  "CLUB ",
  "COMMON ",
  "COMMONS ",
  "CORNER ",
  "CORNERS ",
  "COURSE ",
  "COURT ",
  "COURTS ",
  "COVE ",
  "COVES ",
  "CREEK ",
  "CRESCENT ",
  "CREST ",
  "CROSSING   ",
  "CROSSROAD ",
  "CROSSROADS ",
  "CURVE  ",
  "DALE ",
  "DAM ",
  "DIVIDE ",
  "DRIVE ",
  "DRIVES  ",
  "ESTATE ",
  "ESTATES ",
  "EXPRESSWAY ",
  "EXTENSION ",
  "EXTENSIONS ",
  "FALL ",
  "FALLS ",
  "FERRY ",
  "FIELD ",
  "FIELDS ",
  "FLAT ",
  "FLATS ",
  "FORD ",
  "FORDS ",
  "FOREST ",
  "FORGE ",
  "FORGES ",
  "FORK ",
  "FORKS ",
  "FORT ",
  "FREEWAY ",
  "GARDEN ",
  "GARDENS ",
  "GATEWAY ",
  "GLEN ",
  "GLENS ",
  "GREEN ",
  "GREENS ",
  "GROVE ",
  "GROVES ",
  "HARBOR ",
  "HARBORS ",
  "HAVEN ",
  "HEIGHTS ",
  "HIGHWAY ",
  "HILL ",
  "HILLS ",
  "HOLLOW ",
  "INLET ",
  "ISLAND ",
  "ISLANDS ",
  "ISLE ",
  "JUNCTION ",
  "JUNCTIONS ",
  "KEY ",
  "KEYS ",
  "KNOLL ",
  "KNOLLS ",
  "LAKE ",
  "LAKES ",
  "LAND ",
  "LANDING ",
  "LANE ",
  "LIGHT ",
  "LIGHTS ",
  "LOAF ",
  "LOCK ",
  "LOCKS ",
  "LODGE ",
  "LOOP ",
  "MALL ",
  "MANOR ",
  "MANORS ",
  "MEADOW ",
  "MEADOWS ",
  "MEWS ",
  "MILL ",
  "MILLS ",
  "MISSION ",
  "MOTORWAY ",
  "MOUNT ",
  "MOUNTAIN ",
  "MOUNTAINS ",
  "NECK ",
  "ORCHARD ",
  "OVAL ",
  "OVERPASS ",
  "PARK ",
  "PARKWAY ",
  "PASS ",
  "PASSAGE ",
  "PATH ",
  "PIKE ",
  "PINE ",
  "PINES ",
  "PLACE ",
  "PLAIN ",
  "PLAINS ",
  "PLAZA ",
  "POINT ",
  "POINTS ",
  "PORT ",
  "PORTS ",
  "PRAIRIE ",
  "RADIAL ",
  "RAMP ",
  "RANCH ",
  "RAPID ",
  "RAPIDS ",
  "REST ",
  "RIDGE ",
  "RIDGES ",
  "RIVER ",
  "ROAD ",
  "ROADS ",
  "ROUTE ",
  "ROW ",
  "RUE ",
  "RUN ",
  "SHOAL ",
  "SHOALS ",
  "SHORE ",
  "SHORES ",
  "SKYWAY ",
  "SPRING ",
  "SPRINGS ",
  "SPUR ",
  "SQUARE ",
  "SQUARES ",
  "STATION ",
  "STRAVENUE ",
  "STREAM ",
  "STREET ",
  "STREETS ",
  "SUMMIT ",
  "TERRACE ",
  "THROUGHWAY ",
  "TRACE ",
  "TRACK ",
  "TRAFFICWAY ",
  "TRAIL ",
  "TRAILER ",
  "TUNNEL ",
  "TURNPIKE ",
  "UNDERPASS ",
  "UNION ",
  "UNIONS ",
  "VALLEY ",
  "VALLEYS ",
  "VIADUCT ",
  "VIEW ",
  "VIEWS ",
  "VILLAGE ",
  "VILLAGES ",
  "VILLE ",
  "VISTA ",
  "WALK ",
  "WALL ",
  "WAY ",
  "WAYS ",
  "WELL ",
  "WELLS "
];

export var streetTypesOptions = [];

_.forEach(streetTypes, (st, index) => {
  streetTypesOptions.push({
    id: st,
    text: st,
    alternate: fullStreetTypeName[index]
  });
})


export default htmlStreetTypes;
